// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxu2-WI30ClM8GgtI4eF-KV2N9qeSwFls',
    appId: '1:599618456559:web:409e51d0417302a308041a',
    messagingSenderId: '599618456559',
    projectId: 'brick-brea',
    authDomain: 'brick-brea.firebaseapp.com',
    storageBucket: 'brick-brea.appspot.com',
    measurementId: 'G-Z9V97J5HGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsrgxxdAPVkNTMqbpGb-ZfbhuZ4i3Uh5I',
    appId: '1:599618456559:android:989e9c18720992fd08041a',
    messagingSenderId: '599618456559',
    projectId: 'brick-brea',
    storageBucket: 'brick-brea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPipqT4g_xcM-DeiSENFsS7mGJ1O7Lr5Y',
    appId: '1:599618456559:ios:a20c79f313ec633508041a',
    messagingSenderId: '599618456559',
    projectId: 'brick-brea',
    storageBucket: 'brick-brea.appspot.com',
    iosBundleId: 'com.example.brickBreaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPipqT4g_xcM-DeiSENFsS7mGJ1O7Lr5Y',
    appId: '1:599618456559:ios:848736d953dea46c08041a',
    messagingSenderId: '599618456559',
    projectId: 'brick-brea',
    storageBucket: 'brick-brea.appspot.com',
    iosBundleId: 'com.example.brickBreaker.RunnerTests',
  );
}
